### ISSUE TITLE
Syncing social groups with null location ids kills sync

### ISSUE THREAD

**Issue by batkinson** [cims-bioko/cims-tablet#174]
After running the selenium tests against cims-server, which attempt to create social groups through the web interface, attempting to synchronize social groups on the tablet fails with stack traces like the following:

```
01-19 10:46:00.529 11682-11698/org.openhds.mobile E/SQLiteDatabase: Error inserting groupName=A New Household uuid=b1ad55b973164121a6636e2ea6655e18 location_uuid=null groupHead_uuid=ffffa87b235e4d80a986a291e3fa286e
                                                                    android.database.sqlite.SQLiteConstraintException: socialgroups.location_uuid may not be NULL (code 19)
                                                                        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
                                                                        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:782)
                                                                        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
                                                                        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
                                                                        at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1469)
                                                                        at android.database.sqlite.SQLiteDatabase.insert(SQLiteDatabase.java:1339)
                                                                        at org.openhds.mobile.provider.OpenHDSProvider.insert(OpenHDSProvider.java:639)
                                                                        at android.content.ContentProvider.bulkInsert(ContentProvider.java:981)
                                                                        at org.openhds.mobile.provider.OpenHDSProvider.bulkInsert(OpenHDSProvider.java:368)
                                                                        at android.content.ContentProvider$Transport.bulkInsert(ContentProvider.java:233)
                                                                        at android.content.ContentResolver.bulkInsert(ContentResolver.java:1251)
                                                                        at org.openhds.mobile.repository.RepositoryUtils.bulkInsert(RepositoryUtils.java:30)
                                                                        at org.openhds.mobile.repository.gateway.Gateway.insertMany(Gateway.java:60)
                                                                        at org.openhds.mobile.task.parsing.ParseTask.persistBatch(ParseTask.java:88)
                                                                        at org.openhds.mobile.task.parsing.ParseTask.access$300(ParseTask.java:18)
                                                                        at org.openhds.mobile.task.parsing.ParseTask$ParseHandler.handlePage(ParseTask.java:106)
                                                                        at org.openhds.mobile.task.parsing.XmlPageParser.sendPageToHandler(XmlPageParser.java:145)
                                                                        at org.openhds.mobile.task.parsing.XmlPageParser.parsePages(XmlPageParser.java:117)
                                                                        at org.openhds.mobile.task.parsing.ParseTask.doInBackground(ParseTask.java:58)
                                                                        at org.openhds.mobile.task.parsing.ParseTask.doInBackground(ParseTask.java:18)
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:841)
```

The message is logged multiple times (because we re-attempt batch inserts) until the channel goes unstable and the application dies. For example:

```
01-19 10:46:04.366 1370-1487/system_process W/ActivityManager:   Force finishing activity org.openhds.mobile/.activity.SupervisorMainActivity
01-19 10:46:04.415 1370-1385/system_process D/dalvikvm: GC_FOR_ALLOC freed 550K, 20% free 10064K/12556K, paused 8ms, total 9ms
01-19 10:46:04.415 1370-1385/system_process I/dalvikvm-heap: Grow heap (frag case) to 10.167MB for 281896-byte allocation
01-19 10:46:04.423 1370-1379/system_process D/dalvikvm: GC_FOR_ALLOC freed 60K, 20% free 10279K/12832K, paused 8ms, total 8ms
01-19 10:46:06.044 11682-11682/? D/AndroidRuntime: Shutting down VM
01-19 10:46:06.044 11682-11682/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x42daf120)
01-19 10:46:06.044 11682-11682/? I/Process: Sending signal. PID: 11682 SIG: 9
01-19 10:46:06.064 1370-1399/system_process W/InputDispatcher: channel '21ac8cb0 Toast (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-19 10:46:06.064 1370-1399/system_process E/InputDispatcher: channel '21ac8cb0 Toast (server)' ~ Channel is unrecoverably broken and will be disposed!
01-19 10:46:06.064 1370-1399/system_process W/InputDispatcher: channel '21be3600 org.openhds.mobile/org.openhds.mobile.activity.OpeningActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
01-19 10:46:06.064 1370-1399/system_process E/InputDispatcher: channel '21be3600 org.openhds.mobile/org.openhds.mobile.activity.OpeningActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
01-19 10:46:06.076 1370-1521/system_process I/ActivityManager: Process org.openhds.mobile (pid 11682) has died.
```

**Comment by batkinson** [comment]
The defect that causes an error to clog the sync was reported in #169.
