### ISSUE TITLE
Zsync fails against cims-server 3.0

### ISSUE THREAD

**Issue by batkinson** [cims-bioko/cims-tablet#236]
It appears as though the boundary isn't parsed correctly from the `Content-Type` header when running against cims-server 3.0. It may be that Spring's implementation of range requests adds ';charset=UTF-8` to the end.

The http range request seems to be serviced successfully: http 206, followed with multipart/bytes content. However, the sync fails with the following exception...

```
 08-16 08:12:16.170 5191-8599/org.openhds.mobile:sync E/SyncUtils: sync io failure
                                                                  java.io.EOFException
                                                                      at com.github.batkinson.jrsync.zsync.MultipartByteRangeInputStream.readLine(ZSync.java:538)
                                                                      at com.github.batkinson.jrsync.zsync.MultipartByteRangeInputStream.next(ZSync.java:570)
                                                                      at com.github.batkinson.jrsync.zsync.ZSync.buildFile(ZSync.java:205)
                                                                      at com.github.batkinson.jrsync.zsync.ZSync.sync(ZSync.java:139)
                                                                      at org.openhds.mobile.utilities.SyncUtils.incrementalSync(SyncUtils.java:605)
                                                                      at org.openhds.mobile.utilities.SyncUtils.downloadUpdate(SyncUtils.java:481)
                                                                      at org.openhds.mobile.syncadpt.SyncAdapter.onPerformSync(SyncAdapter.java:33)
                                                                      at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:259)
```

[failed-range-request-packet-capture.gz](https://github.com/cims-bioko/cims-tablet/files/1227623/failed-range-request-packet-capture.gz)

**Comment by batkinson** [comment]
This appears to be a defect in zsync. It does not handle the trailing encoding parameter properly (it should not include it as part of the parameter).
