### ISSUE TITLE
App crashes when launching a form on Android N

### ISSUE THREAD

**Issue by batkinson** [cims-bioko/cims-tablet#274]
When attempting to launch a form on a Galaxy Tab A running Android N, the app crashes. You get the following exception:

```
08-01 13:02:28.795 19335-19335/org.openhds.mobile I/art: Rejecting re-init on previously-failed class java.lang.Class<org.jdom2.ContentList>: java.lang.IllegalAccessError: Method 'void org.jdom2.ContentList.sort(java.util.Comparator)' implementing interface method 'void java.util.List.sort(java.util.Comparator)' is not public (declaration of 'org.jdom2.ContentList' appears in /data/app/org.openhds.mobile-1/base.apk)
        at void org.jdom2.Document.<init>(org.jdom2.Element, org.jdom2.DocType, java.lang.String) (Document.java:83)
        at void org.jdom2.Document.<init>(org.jdom2.Element) (Document.java:154)
        at org.jdom2.Document org.jdom2.DefaultJDOMFactory.document(org.jdom2.Element) (DefaultJDOMFactory.java:190)
        at void org.jdom2.input.sax.SAXHandler.reset() (SAXHandler.java:228)
        at void org.jdom2.input.sax.SAXHandler.<init>(org.jdom2.JDOMFactory) (SAXHandler.java:208)
        at void org.jdom2.input.sax.DefaultSAXHandlerFactory$DefaultSAXHandler.<init>(org.jdom2.JDOMFactory) (DefaultSAXHandlerFactory.java:76)
        at org.jdom2.input.sax.SAXHandler org.jdom2.input.sax.DefaultSAXHandlerFactory.createSAXHandler(org.jdom2.JDOMFactory) (DefaultSAXHandlerFactory.java:82)
        at org.jdom2.input.sax.SAXEngine org.jdom2.input.SAXBuilder.buildEngine() (SAXBuilder.java:848)
        at org.jdom2.input.sax.SAXEngine org.jdom2.input.SAXBuilder.getEngine() (SAXBuilder.java:904)
        at org.jdom2.Document org.jdom2.input.SAXBuilder.build(java.io.File) (SAXBuilder.java:1116)
        at org.jdom2.Document org.openhds.mobile.utilities.FormUtils.domFromFile(java.io.File) (FormUtils.java:61)
        at org.jdom2.Document org.openhds.mobile.utilities.FormUtils.genInstanceDoc(java.io.File, java.util.Map) (FormUtils.java:208)
        at android.net.Uri org.openhds.mobile.utilities.FormUtils.generateODKForm(android.content.ContentResolver, org.openhds.mobile.navconfig.forms.Binding, org.openhds.mobile.model.form.FormInstance, java.util.Map, java.io.File) (FormUtils.java:324)
        at android.net.Uri org.openhds.mobile.model.form.FormInstance.generate(android.content.ContentResolver, org.openhds.mobile.navconfig.forms.Binding, java.util.Map) (FormInstance.java:171)
        at void org.openhds.mobile.activity.HierarchyNavigatorActivity.launchNewForm(org.openhds.mobile.navconfig.forms.Binding) (HierarchyNavigatorActivity.java:243)
        at void org.openhds.mobile.activity.HierarchyNavigatorActivity.onFormSelected(org.openhds.mobile.navconfig.forms.Binding) (HierarchyNavigatorActivity.java:308)
        at void org.openhds.mobile.fragment.FormSelectionFragment$FormClickListener.onItemClick(android.widget.AdapterView, android.view.View, int, long) (FormSelectionFragment.java:68)
        at boolean android.widget.AdapterView.performItemClick(android.view.View, int, long) (AdapterView.java:343)
        at boolean android.widget.AbsListView.performItemClick(android.view.View, int, long) (AbsListView.java:1665)
        at void android.widget.AbsListView$PerformClick.run() (AbsListView.java:4075)
        at void android.widget.AbsListView$10.run() (AbsListView.java:6552)
        at void android.os.Handler.handleCallback(android.os.Message) (Handler.java:751)
        at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:95)
        at void android.os.Looper.loop() (Looper.java:154)
        at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6823)
        at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
        at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:1563)
        at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:1451)
08-01 13:02:28.799 19335-19335/org.openhds.mobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.openhds.mobile, PID: 19335
    java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jdom2/ContentList;
        at org.jdom2.Document.<init>(Document.java:83)
        at org.jdom2.Document.<init>(Document.java:154)
        at org.jdom2.DefaultJDOMFactory.document(DefaultJDOMFactory.java:190)
        at org.jdom2.input.sax.SAXHandler.reset(SAXHandler.java:228)
        at org.jdom2.input.sax.SAXHandler.<init>(SAXHandler.java:208)
        at org.jdom2.input.sax.DefaultSAXHandlerFactory$DefaultSAXHandler.<init>(DefaultSAXHandlerFactory.java:76)
        at org.jdom2.input.sax.DefaultSAXHandlerFactory.createSAXHandler(DefaultSAXHandlerFactory.java:82)
        at org.jdom2.input.SAXBuilder.buildEngine(SAXBuilder.java:848)
        at org.jdom2.input.SAXBuilder.getEngine(SAXBuilder.java:904)
        at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1116)
        at org.openhds.mobile.utilities.FormUtils.domFromFile(FormUtils.java:61)
        at org.openhds.mobile.utilities.FormUtils.genInstanceDoc(FormUtils.java:208)
        at org.openhds.mobile.utilities.FormUtils.generateODKForm(FormUtils.java:324)
        at org.openhds.mobile.model.form.FormInstance.generate(FormInstance.java:171)
        at org.openhds.mobile.activity.HierarchyNavigatorActivity.launchNewForm(HierarchyNavigatorActivity.java:243)
        at org.openhds.mobile.activity.HierarchyNavigatorActivity.onFormSelected(HierarchyNavigatorActivity.java:308)
        at org.openhds.mobile.fragment.FormSelectionFragment$FormClickListener.onItemClick(FormSelectionFragment.java:68)
        at android.widget.AdapterView.performItemClick(AdapterView.java:343)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1665)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:4075)
        at android.widget.AbsListView$10.run(AbsListView.java:6552)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
     Caused by: java.lang.ClassNotFoundException: org.jdom2.ContentList
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.jdom2.Document.<init>(Document.java:83) 
        at org.jdom2.Document.<init>(Document.java:154) 
        at org.jdom2.DefaultJDOMFactory.document(DefaultJDOMFactory.java:190) 
        at org.jdom2.input.sax.SAXHandler.reset(SAXHandler.java:228) 
        at org.jdom2.input.sax.SAXHandler.<init>(SAXHandler.java:208) 
        at org.jdom2.input.sax.DefaultSAXHandlerFactory$DefaultSAXHandler.<init>(DefaultSAXHandlerFactory.java:76) 
        at org.jdom2.input.sax.DefaultSAXHandlerFactory.createSAXHandler(DefaultSAXHandlerFactory.java:82) 
        at org.jdom2.input.SAXBuilder.buildEngine(SAXBuilder.java:848) 
        at org.jdom2.input.SAXBuilder.getEngine(SAXBuilder.java:904) 
        at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1116) 
        at org.openhds.mobile.utilities.FormUtils.domFromFile(FormUtils.java:61) 
        at org.openhds.mobile.utilities.FormUtils.genInstanceDoc(FormUtils.java:208) 
        at org.openhds.mobile.utilities.FormUtils.generateODKForm(FormUtils.java:324) 
        at org.openhds.mobile.model.form.FormInstance.generate(FormInstance.java:171) 
        at org.openhds.mobile.activity.HierarchyNavigatorActivity.launchNewForm(HierarchyNavigatorActivity.java:243) 
        at org.openhds.mobile.activity.HierarchyNavigatorActivity.onFormSelected(HierarchyNavigatorActivity.java:308) 
        at org.openhds.mobile.fragment.FormSelectionFragment$FormClickListener.onItemClick(FormSelectionFragment.java:68) 
        at android.widget.AdapterView.performItemClick(AdapterView.java:343) 
        at android.widget.AbsListView.performItemClick(AbsListView.java:1665) 
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:4075) 
        at android.widget.AbsListView$10.run(AbsListView.java:6552) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6823) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451) 
     Caused by: java.lang.IllegalAccessError: Method 'void org.jdom2.ContentList.sort(java.util.Comparator)' implementing interface method 'void java.util.List.sort(java.util.Comparator)' is not public (declaration of 'org.jdom2.ContentList' appears in /data/app/org.openhds.mobile-1/base.apk)
        at org.jdom2.Document.<init>(Document.java:83) 
        at org.jdom2.Document.<init>(Document.java:154) 
        at org.jdom2.DefaultJDOMFactory.document(DefaultJDOMFactory.java:190) 
        at org.jdom2.input.sax.SAXHandler.reset(SAXHandler.java:228) 
        at org.jdom2.input.sax.SAXHandler.<init>(SAXHandler.java:208) 
        at org.jdom2.input.sax.DefaultSAXHandlerFactory$DefaultSAXHandler.<init>(DefaultSAXHandlerFactory.java:76) 
        at org.jdom2.input.sax.DefaultSAXHandlerFactory.createSAXHandler(DefaultSAXHandlerFactory.java:82) 
        at org.jdom2.input.SAXBuilder.buildEngine(SAXBuilder.java:848) 
        at org.jdom2.input.SAXBuilder.getEngine(SAXBuilder.java:904) 
        at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1116) 
        at org.openhds.mobile.utilities.FormUtils.domFromFile(FormUtils.java:61) 
        at org.openhds.mobile.utilities.FormUtils.genInstanceDoc(FormUtils.java:208) 
        at org.openhds.mobile.utilities.FormUtils.generateODKForm(FormUtils.java:324) 
        at org.openhds.mobile.model.form.FormInstance.generate(FormInstance.java:171) 
        at org.openhds.mobile.activity.HierarchyNavigatorActivity.launchNewForm(HierarchyNavigatorActivity.java:243) 
        at org.openhds.mobile.activity.HierarchyNavigatorActivity.onFormSelected(HierarchyNavigatorActivity.java:308) 
        at org.openhds.mobile.fragment.FormSelectionFragment$FormClickListener.onItemClick(FormSelectionFragment.java:68) 
        at android.widget.AdapterView.performItemClick(AdapterView.java:343) 
        at android.widget.AbsListView.performItemClick(AbsListView.java:1665) 
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:4075) 
        at android.widget.AbsListView$10.run(AbsListView.java:6552) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6823) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451) 
```

**Comment by batkinson** [comment]
See https://stackoverflow.com/questions/39268486/android-illegalaccesserror-on-nougat
